export const data = {
    "TotalCount": 17,
    "Result": [
        {
            "HasOrganization": false,
            "Id": 3824328,
            "ExternalIdentifier": 2,
            "Name": "Barcode Adult Single Trip",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 275,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "120 minutes from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T11:04:21.000Z",
            "ValidTo": "2022-02-17T13:04:21.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3827236,
            "ExternalIdentifier": 5,
            "Name": "Mã vạch chuyến đi duy nhất",
            "Description": "Single Trip Adult Barcode",
            "FareCategory": 5,
            "ProductGroup": null,
            "Type": 3,
            "Price": 275,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "120 minutes from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T11:04:21.000Z",
            "ValidTo": "2022-02-17T13:04:21.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3827298,
            "ExternalIdentifier": 6,
            "Name": "Student Single Trip Barcode",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 175,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "120 minutes from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T11:04:21.000Z",
            "ValidTo": "2022-02-17T13:04:21.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824704,
            "ExternalIdentifier": 100,
            "Name": "Adult 1-Day Pass EN",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 550,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Valid until the end of the service day from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T02:00:00.000Z",
            "ValidTo": "2022-02-18T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824689,
            "ExternalIdentifier": 101,
            "Name": "Adult 1-Month Pass",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 7000,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Current calendar month. Pass for the next month can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the month and ends at 3am on the last business day of the month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2022-03-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2022-03-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824674,
            "ExternalIdentifier": 102,
            "Name": "Adult 12-Month Pass",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 77000,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "One year starting with the current month. First of current month is preselected as start date. Pass for the next year can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the first month and ends at 3am on the last business day of the last month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2023-02-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2023-02-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824764,
            "ExternalIdentifier": 200,
            "Name": "Youth 1-Day Pass",
            "Description": "",
            "FareCategory": 2,
            "ProductGroup": null,
            "Type": 3,
            "Price": 250,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Valid until the end of the service day from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T02:00:00.000Z",
            "ValidTo": "2022-02-18T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824749,
            "ExternalIdentifier": 201,
            "Name": "Youth 1-Month Pass",
            "Description": "",
            "FareCategory": 2,
            "ProductGroup": null,
            "Type": 3,
            "Price": 3500,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Current calendar month. Pass for the next month can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the month and ends at 3am on the last business day of the month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2022-03-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2022-03-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824734,
            "ExternalIdentifier": 202,
            "Name": "Youth 12-Month Pass",
            "Description": "",
            "FareCategory": 2,
            "ProductGroup": null,
            "Type": 3,
            "Price": 38500,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "One year starting with the current month. First of current month is preselected as start date. Pass for the next year can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the first month and ends at 3am on the last business day of the last month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2023-02-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2023-02-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824463,
            "ExternalIdentifier": 300,
            "Name": "Senior 1-Day Pass",
            "Description": "",
            "FareCategory": 3,
            "ProductGroup": null,
            "Type": 3,
            "Price": 200,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Valid until the end of the service day from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T02:00:00.000Z",
            "ValidTo": "2022-02-18T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824433,
            "ExternalIdentifier": 301,
            "Name": "Senior 1-Month Pass",
            "Description": "",
            "FareCategory": 3,
            "ProductGroup": null,
            "Type": 3,
            "Price": 600,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Current calendar month. Pass for the next month can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the month and ends at 3am on the last business day of the month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2022-03-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2022-03-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824448,
            "ExternalIdentifier": 302,
            "Name": "Senior 12-Month Pass",
            "Description": "",
            "FareCategory": 3,
            "ProductGroup": null,
            "Type": 3,
            "Price": 3500,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "One year starting with the current month. First of current month is preselected as start date. Pass for the next year can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the first month and ends at 3am on the last business day of the last month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2023-02-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2023-02-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824493,
            "ExternalIdentifier": 400,
            "Name": "Disabled 1-Month Pass",
            "Description": "",
            "FareCategory": 4,
            "ProductGroup": null,
            "Type": 3,
            "Price": 600,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Current calendar month. Pass for the next month can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the month and ends at 3am on the last business day of the month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2022-03-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2022-03-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824478,
            "ExternalIdentifier": 401,
            "Name": "Disabled 12-Month Pass",
            "Description": "",
            "FareCategory": 4,
            "ProductGroup": null,
            "Type": 3,
            "Price": 3500,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "One year starting with the current month. First of current month is preselected as start date. Pass for the next year can be sold on the 20th of the current month. Validity starts at 12am on the fist business day of the first month and ends at 3am on the last business day of the last month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-31T23:00:00.000Z",
            "ValidTo": "2023-02-01T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-31T23:00:00.000Z",
                    "ValidTo": "2023-02-01T02:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824553,
            "ExternalIdentifier": 402,
            "Name": "Disabled 1-Day Pass",
            "Description": "",
            "FareCategory": 4,
            "ProductGroup": null,
            "Type": 3,
            "Price": 200,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Valid until the end of the service day from first use.",
            "IsValidWhenSelling": false,
            "ValidFrom": "2022-02-17T02:00:00.000Z",
            "ValidTo": "2022-02-18T02:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824523,
            "ExternalIdentifier": 503,
            "Name": "Spring College Semester Pass",
            "Description": "",
            "FareCategory": 1,
            "ProductGroup": null,
            "Type": 3,
            "Price": 25000,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": "Valid from January 1st - May 31st (5 Months).  Pass can be sold on the 15th of the prior month.",
            "IsValidWhenSelling": true,
            "ValidFrom": "2022-01-01T02:00:00.000Z",
            "ValidTo": "2022-06-01T01:00:00.000Z",
            "NumberOfTrips": null,
            "LoadingLimit": null,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": 3,
            "ValidityDates": [
                {
                    "ValidFrom": "2022-01-01T02:00:00.000Z",
                    "ValidTo": "2022-06-01T01:00:00.000Z",
                    "IsDefaultFrom": true
                }
            ],
            "IsOfflineAvailable": false
        },
        {
            "HasOrganization": false,
            "Id": 3824613,
            "ExternalIdentifier": 1000,
            "Name": "Reload EN",
            "Description": "Reload D EN",
            "FareCategory": 0,
            "ProductGroup": null,
            "Type": 8,
            "Price": 0,
            "ValuePassCredit": null,
            "SubsidizedPayment": null,
            "ValidityDescription": null,
            "IsValidWhenSelling": null,
            "ValidFrom": null,
            "ValidTo": null,
            "NumberOfTrips": null,
            "LoadingLimit": 20000,
            "IsProratable": false,
            "GroupSize": null,
            "OperatorId": null,
            "ValidityDates": [],
            "IsOfflineAvailable": false
        }
    ]
}